/**
 * Campaign batch helpers — server-side only.
 *
 * Manages campaign_batches and campaign_items tables.
 * One batch = one OpenAI-generated campaign plan (8 items by default).
 * Items hold individual video concepts; they graduate to full reels when
 * Kie/Seedance generates a video (future step).
 *
 * Follows the same Supabase service-role pattern as reels-db.ts:
 *   - Plain .insert() without .select() to avoid RLS SELECT blocks
 *   - IDs are pre-generated by caller so we can return constructed objects
 */

import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";

// ─── Client ───────────────────────────────────────────────────────────────────

function getClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key)
    throw new Error(
      "Supabase is not configured — set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY."
    );
  return createClient(url, key);
}

/**
 * Turns a Supabase PostgrestError (or any unknown error value) into a
 * human-readable string that is never "undefined".
 *
 * Supabase errors are plain objects — NOT Error instances — so
 * `error instanceof Error` is false and `error.message` can be undefined
 * depending on the client version and error source.
 */
function serializeError(error: unknown): string {
  if (!error) return "unknown error (null/undefined)";
  if (typeof error === "string") return error;
  if (error instanceof Error) return error.message;

  // Supabase PostgrestError: { message?, code?, details?, hint? }
  const e = error as Record<string, unknown>;
  const parts: string[] = [];
  if (e["message"]) parts.push(String(e["message"]));
  if (e["code"])    parts.push(`code=${String(e["code"])}`);
  if (e["details"]) parts.push(`details=${String(e["details"])}`);
  if (e["hint"])    parts.push(`hint=${String(e["hint"])}`);
  if (parts.length > 0) return parts.join(" | ");

  try {
    return JSON.stringify(error);
  } catch {
    return String(error);
  }
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CampaignBatch {
  id: string;
  created_at: string;
  updated_at: string;
  user_key: string;
  workspace_key: string;
  brand_name: string | null;
  batch_title: string | null;
  batch_type: string | null;
  instruction: string | null;
  reference_image_url: string | null;
  status: string;
  /** Social post caption for Library/Post Now. NOT inserted into video prompts. */
  post_caption: string | null;
  /** Full tagged reference image list (tag, info, name, url). Stored as JSONB. */
  reference_images: Array<{ tag: string; info?: string; name?: string; url: string }> | null;
}

export interface CampaignItem {
  id: string;
  created_at: string;
  updated_at: string;
  user_key: string;
  workspace_key: string;
  batch_id: string | null;
  title: string | null;
  ad_type: string | null;
  hook: string | null;
  prompt_text: string | null;
  caption: string | null;
  reason: string | null;
  platform: string | null;
  duration_seconds: number;
  aspect_ratio: string;
  resolution: string;
  model: string;
  status: string;
  kie_task_id: string | null;
  video_url: string | null;
  thumbnail_url: string | null;
  error_message: string | null;
}

export interface CreateItemData {
  title: string;
  adType: string;
  hook: string;
  promptText: string;
  caption: string;
  reason: string;
  platform: string;
  durationSeconds?: number;
  aspectRatio?: string;
  resolution?: string;
  model?: string;
}

export interface CreateCampaignBatchInput {
  workspaceKey?: string;
  userKey?: string;
  brandName?: string;
  batchTitle?: string;
  batchType?: string;
  instruction?: string;
  referenceImageUrl?: string;
  /** Social post caption for Library/Post Now — NOT for Seedance video generation. */
  postCaption?: string;
  /** All tagged reference images — tag, info, name, url. Saved as JSONB. */
  referenceImages?: Array<{ tag: string; info?: string; name?: string; url: string }>;
  items: CreateItemData[];
}

// ─── CRUD ─────────────────────────────────────────────────────────────────────

/**
 * Insert a campaign_batches row and all its campaign_items in one call.
 *
 * Uses plain .insert() (no .select()) for the batch row to avoid the RLS
 * SELECT block pattern. IDs are pre-generated so we return constructed
 * objects without needing to re-fetch.
 */
export async function createCampaignBatchWithItems(
  input: CreateCampaignBatchInput
): Promise<{ batch: CampaignBatch; items: CampaignItem[] }> {
  const supabase = getClient();

  const workspaceKey = input.workspaceKey ?? "gotjesus";
  const userKey = input.userKey ?? "demo_jordan";
  const now = new Date().toISOString();
  const batchId = randomUUID();

  // 1 — Insert batch row
  const batchRow = {
    id: batchId,
    created_at: now,
    updated_at: now,
    user_key: userKey,
    workspace_key: workspaceKey,
    brand_name: input.brandName ?? null,
    batch_title: input.batchTitle ?? null,
    batch_type: input.batchType ?? null,
    instruction: input.instruction ?? null,
    reference_image_url: input.referenceImageUrl ?? null,
    post_caption: input.postCaption ?? null,
    reference_images: input.referenceImages ?? [],
    status: "planned",
  };

  const { error: batchError } = await supabase
    .from("campaign_batches")
    .insert(batchRow);

  if (batchError) {
    console.error("[campaign-batches] campaign_batches insert error:", batchError);
    const errStr = serializeError(batchError);
    const isPgrst204 =
      errStr.includes("PGRST204") ||
      errStr.toLowerCase().includes("could not find") ||
      (batchError as unknown as Record<string, unknown>)["code"] === "PGRST204";
    if (isPgrst204) {
      throw new Error(
        "Supabase column missing (PGRST204). Run this SQL:\n" +
        "alter table campaign_batches add column if not exists post_caption text;\n" +
        "alter table campaign_batches add column if not exists reference_images jsonb not null default '[]'::jsonb;"
      );
    }
    throw new Error(`createCampaignBatch failed: ${errStr}`);
  }

  console.log(`[campaign-batches] Inserted batch ${batchId}`);

  // 2 — Insert all items
  const itemRows = input.items.map((item) => {
    const itemId = randomUUID();
    return {
      id: itemId,
      created_at: now,
      updated_at: now,
      user_key: userKey,
      workspace_key: workspaceKey,
      batch_id: batchId,
      title: item.title,
      ad_type: item.adType,
      hook: item.hook,
      prompt_text: item.promptText,
      caption: item.caption,
      reason: item.reason,
      platform: item.platform,
      duration_seconds: item.durationSeconds ?? 8,
      aspect_ratio: item.aspectRatio ?? "9:16",
      resolution: item.resolution ?? "480p",
      model: item.model ?? "Seedance 2.0 Fast",
      status: "planned",
      kie_task_id: null,
      video_url: null,
      thumbnail_url: null,
      error_message: null,
    };
  });

  const { error: itemsError } = await supabase
    .from("campaign_items")
    .insert(itemRows);

  if (itemsError) {
    console.error("[campaign-batches] campaign_items insert error:", itemsError);
    throw new Error(
      `campaign_items insert failed (batch ${batchId} was saved): ${serializeError(itemsError)}`
    );
  }

  console.log(
    `[campaign-batches] Inserted ${itemRows.length} items for batch ${batchId}`
  );

  // 3 — Construct return values from input (no re-fetch)
  const batch: CampaignBatch = {
    id: batchId,
    created_at: now,
    updated_at: now,
    user_key: userKey,
    workspace_key: workspaceKey,
    brand_name: input.brandName ?? null,
    batch_title: input.batchTitle ?? null,
    batch_type: input.batchType ?? null,
    instruction: input.instruction ?? null,
    reference_image_url: input.referenceImageUrl ?? null,
    post_caption: input.postCaption ?? null,
    reference_images: input.referenceImages ?? [],
    status: "planned",
  };

  const items: CampaignItem[] = itemRows.map((row) => ({
    id: row.id,
    created_at: row.created_at,
    updated_at: row.updated_at,
    user_key: row.user_key,
    workspace_key: row.workspace_key,
    batch_id: row.batch_id,
    title: row.title,
    ad_type: row.ad_type,
    hook: row.hook,
    prompt_text: row.prompt_text,
    caption: row.caption,
    reason: row.reason,
    platform: row.platform,
    duration_seconds: row.duration_seconds,
    aspect_ratio: row.aspect_ratio,
    resolution: row.resolution,
    model: row.model,
    status: row.status,
    kie_task_id: row.kie_task_id,
    video_url: row.video_url,
    thumbnail_url: row.thumbnail_url,
    error_message: row.error_message,
  }));

  return { batch, items };
}

/**
 * Returns all batches for a workspace, most recent first.
 */
export async function getCampaignBatches(
  workspaceKey = "gotjesus",
  limit = 20
): Promise<CampaignBatch[]> {
  const supabase = getClient();
  const { data, error } = await supabase
    .from("campaign_batches")
    .select("*")
    .eq("workspace_key", workspaceKey)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    console.warn("[campaign-batches] getCampaignBatches:", error.message);
    return [];
  }
  return (data ?? []) as CampaignBatch[];
}

/**
 * Returns all items for a specific batch.
 */
export async function getCampaignItems(batchId: string): Promise<CampaignItem[]> {
  const supabase = getClient();
  const { data, error } = await supabase
    .from("campaign_items")
    .select("*")
    .eq("batch_id", batchId)
    .order("created_at", { ascending: true });

  if (error) {
    console.warn(`[campaign-batches] getCampaignItems(${batchId}):`, error.message);
    return [];
  }
  return (data ?? []) as CampaignItem[];
}

/**
 * Returns a single campaign item by id, or null if not found.
 */
export async function getCampaignItemById(id: string): Promise<CampaignItem | null> {
  const supabase = getClient();
  const { data, error } = await supabase
    .from("campaign_items")
    .select("*")
    .eq("id", id)
    .single();

  if (error) {
    if (error.code === "PGRST116") return null; // not found
    console.warn(`[campaign-batches] getCampaignItemById(${id}):`, error.message);
    return null;
  }
  return data as CampaignItem;
}

/**
 * Returns a single campaign batch by id, or null if not found.
 */
export async function getCampaignBatchById(id: string): Promise<CampaignBatch | null> {
  const supabase = getClient();
  const { data, error } = await supabase
    .from("campaign_batches")
    .select("*")
    .eq("id", id)
    .single();

  if (error) {
    if (error.code === "PGRST116") return null; // not found
    console.warn(`[campaign-batches] getCampaignBatchById(${id}):`, error.message);
    return null;
  }
  return data as CampaignBatch;
}

/**
 * Partially updates a campaign_items row.
 * Uses plain .update() without .select() to avoid RLS SELECT blocks.
 */
export async function updateCampaignItem(
  id: string,
  patch: Partial<Pick<
    CampaignItem,
    | "status"
    | "kie_task_id"
    | "video_url"
    | "thumbnail_url"
    | "error_message"
  >>
): Promise<void> {
  const supabase = getClient();
  const { error } = await supabase
    .from("campaign_items")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id);

  if (error) {
    throw new Error(`updateCampaignItem(${id}) failed: ${error.message}`);
  }
}
